
CREATE TABLE QUARTO( 
    NUMERO INTEGER PRIMARY KEY);

CREATE TABLE ENFERMIDADE( 
    CID VARCHAR(255) PRIMARY KEY,
	nome VARCHAR(255));

CREATE TABLE MEDICAMENTO( 
    CODIGO NUMBER(6) PRIMARY KEY,
	NOME VARCHAR(255));

CREATE TABLE MEDICO( 
    CPF VARCHAR(11) PRIMARY KEY, 
    NOME VARCHAR(50) NOT NULL, 
    CIDADE VARCHAR(75), 
    RUA VARCHAR(75), 
    CRM VARCHAR(10) NOT NULL UNIQUE, 
    SUPERVISOR VARCHAR(11), 
    CONSTRAINT FK_MED FOREIGN KEY (SUPERVISOR) REFERENCES MEDICO(CPF));

CREATE TABLE PACIENTE( 
    CPF VARCHAR(11) PRIMARY KEY, 
    NOME VARCHAR(50) NOT NULL, 
    CIDADE VARCHAR(30), 
    RUA VARCHAR(75), 
    N_QUARTO INTEGER, 
    CONSTRAINT FK_QUARTO_PACIENTE FOREIGN KEY (N_QUARTO) REFERENCES QUARTO(NUMERO));

CREATE TABLE CONTATO_FAMILIAR( 
    CPF VARCHAR(11), 
    TELEFONE VARCHAR(12), 
    NOME VARCHAR(50) NOT NULL, 
    CONSTRAINT PK_CONTATO PRIMARY KEY(CPF, TELEFONE), 
    CONSTRAINT FK_CONTATO_PACIENTE FOREIGN KEY(TELEFONE) REFERENCES PACIENTE(CPF));

CREATE TABLE ARTE( 
    CPF VARCHAR(11), 
    DAT DATE, 
    CONSTRAINT PK_ARTE PRIMARY KEY(CPF, DAT));

CREATE TABLE TRATA( 
    CPF_MEDICO VARCHAR(11), 
    CPF_PACIENTE VARCHAR(11), 
    CID VARCHAR(255), 
    DATA_TRATA DATE, 
    CONSTRAINT PK_TRATA PRIMARY KEY(CPF_MEDICO, CPF_PACIENTE, CID, DATA_TRATA), 
    CONSTRAINT FK_TRATA_MEDICO FOREIGN KEY(CPF_MEDICO) REFERENCES MEDICO(CPF), 
    CONSTRAINT FK_TRATA_PACIENTE FOREIGN KEY(CPF_PACIENTE) REFERENCES PACIENTE(CPF), 
    CONSTRAINT FK_TRATA_ENFERMIDADE FOREIGN KEY(CID) REFERENCES ENFERMIDADE(CID));

CREATE TABLE UTILIZA( 
    CPF_MEDICO VARCHAR(11), 
    CPF_PACIENTE VARCHAR(11), 
    CID VARCHAR(255), 
    DATA_UTILIZA DATE, 
    CODIGO NUMBER(6), 
    CONSTRAINT PK_UTILIZA PRIMARY KEY(CPF_MEDICO, CPF_PACIENTE, CID, DATA_UTILIZA, CODIGO), 
    CONSTRAINT FK_UTILIZA_TRATA FOREIGN KEY (CPF_MEDICO, CPF_PACIENTE, CID, DATA_UTILIZA) REFERENCES TRATA(CPF_MEDICO, CPF_PACIENTE, CID, DATA_TRATA), 
    CONSTRAINT FK_UTILIZA_MEDICAMENTO FOREIGN KEY (CODIGO) REFERENCES MEDICAMENTO(CODIGO));

