CREATE OR REPLACE TRIGGER QUARTO_LOTADO BEFORE INSERT OR UPDATE OF N_QUARTO ON PACIENTE
FOR EACH ROW
DECLARE
    CONTADOR NUMBER;
BEGIN
    SELECT COUNT(*) INTO CONTADOR FROM PACIENTE WHERE N_QUARTO = :NEW.N_QUARTO;  --new é o valor novo, old. teria o valor antigo
    IF CONTADOR > 3 THEN
        RAISE_APPLICATION_ERROR(-20205,'O quarto está cheio');
    END IF;
END;

